import React from 'react';
import {
  Brain,
  Sparkles,
  ArrowLeft,
  CheckCircle2,
  AlertTriangle,
  HeartPulse,
  TrendingUp,
  Clock,
  BookOpen,
} from 'lucide-react';
import { TeacherStudentItem } from '../../types.ts';

interface StudentInsightsViewProps {
  student: TeacherStudentItem | null;
  onBack: () => void;
  onAssignIntervention: (studentName: string) => void;
}

export const StudentInsightsView: React.FC<StudentInsightsViewProps> = ({
  student,
  onBack,
  onAssignIntervention,
}) => {
  const current = student || {
    id: 'usr_student_1',
    name: 'Siva',
    overallMastery: 72,
    momentum: 12,
    status: 'On Track' as const,
    strengths: ['Probability Foundations', 'Data Structures', 'Python for AI'],
    gaps: ['Conditional Probability', 'Bayes Theorem'],
    lastActive: '10 mins ago',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-200">
      {/* Top Header with Back button from Screen 19 */}
      <div className="flex items-center justify-between pb-4 border-b border-slate-200">
        <div className="flex items-center gap-3">
          <button
            onClick={onBack}
            className="p-2 bg-white hover:bg-slate-100 border border-slate-200 rounded-xl text-slate-600 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
          </button>
          <div>
            <h1 className="text-xl sm:text-2xl font-extrabold text-slate-900 tracking-tight">
              Student Twin Insights: {current.name}
            </h1>
            <p className="text-xs text-slate-500">
              Granular cognitive diagnostic breakdown generated by the learning twin.
            </p>
          </div>
        </div>

        <button
          onClick={() => onAssignIntervention(current.name)}
          className="px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white font-bold text-xs rounded-xl shadow-xs transition-colors flex items-center gap-1.5"
        >
          <Sparkles className="w-3.5 h-3.5" />
          <span>Assign Targeted Remediation</span>
        </button>
      </div>

      {/* Profile Snapshot Banner (Screen 19 from Reference) */}
      <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200 shadow-xs flex flex-col sm:flex-row items-center justify-between gap-6">
        <div className="flex items-center gap-5">
          <div className="w-20 h-20 rounded-2xl overflow-hidden border-2 border-indigo-500/20 shadow-md">
            <img
              src={current.avatarUrl}
              alt={current.name}
              className="w-full h-full object-cover"
              referrerPolicy="no-referrer"
            />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-2xl font-extrabold text-slate-900">{current.name}</h2>
              <span
                className={`px-2.5 py-0.5 rounded-full text-xs font-bold ${
                  current.status === 'On Track'
                    ? 'bg-emerald-100 text-emerald-800'
                    : 'bg-rose-100 text-rose-800'
                }`}
              >
                {current.status}
              </span>
            </div>
            <p className="text-xs text-slate-500 mt-1">
              AI & Data Science • Last Active {current.lastActive}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-6">
          <div className="text-right">
            <div className="text-3xl font-extrabold text-indigo-600">{current.overallMastery}%</div>
            <div className="text-xs font-semibold text-slate-400">Current Mastery</div>
          </div>
          <div className="text-right">
            <div className="text-3xl font-extrabold text-emerald-600">+{current.momentum}%</div>
            <div className="text-xs font-semibold text-slate-400">Velocity</div>
          </div>
        </div>
      </div>

      {/* Strengths & Gaps Two-Column Breakdown */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-start">
        {/* Confirmed Strengths */}
        <div className="bg-white rounded-3xl p-6 border border-slate-200 shadow-xs space-y-4">
          <div className="flex items-center gap-2 text-emerald-700 font-bold text-sm">
            <CheckCircle2 className="w-5 h-5" />
            <span>Mastered Concepts (Strengths)</span>
          </div>

          <div className="space-y-2.5">
            {(current.strengths || []).map((str, idx) => (
              <div
                key={idx}
                className="p-3.5 rounded-2xl bg-emerald-50/70 border border-emerald-200 text-xs flex items-center justify-between"
              >
                <span className="font-bold text-emerald-950">{str}</span>
                <span className="font-extrabold text-emerald-700">&gt;80%</span>
              </div>
            ))}
          </div>
        </div>

        {/* Active Knowledge Gaps */}
        <div className="bg-white rounded-3xl p-6 border border-slate-200 shadow-xs space-y-4">
          <div className="flex items-center gap-2 text-rose-700 font-bold text-sm">
            <AlertTriangle className="w-5 h-5" />
            <span>Prerequisite Bottlenecks (Gaps)</span>
          </div>

          <div className="space-y-2.5">
            {((current.gaps || (current as any).knowledgeGaps) || []).map((gap: string, idx: number) => (
              <div
                key={idx}
                className="p-3.5 rounded-2xl bg-rose-50/70 border border-rose-200 text-xs flex items-center justify-between"
              >
                <div>
                  <span className="font-bold text-rose-950">{gap}</span>
                  <div className="text-[10px] text-rose-700 font-medium">Blocking downstream modules</div>
                </div>
                <span className="font-extrabold text-rose-600">&lt;50%</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
